# Generated by Django 4.1.3 on 2023-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_cliente_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="nivel",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
